# Generated by Django 5.0 on 2023-12-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JWTApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailsmodel",
            name="username",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
